language: java

sudo: false   # Linux OS: run in container

services:
  - docker

matrix:
  include:
    # Headed Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
          - CODACY_PROJECT_TOKEN=30ded88adc3944479b2de1780b26f01b
    # Headless Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
        - CODACY_PROJECT_TOKEN=30ded88adc3944479b2de1780b26f01b
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    # Headless macOS
    - os: osx
      osx_image: xcode9
      env:
        - CODACY_PROJECT_TOKEN=30ded88adc3944479b2de1780b26f01b
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    # Headed macOS is not currently possible on Travis.

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask reinstall caskroom/versions/java8; fi

install: true

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack:
    secure: XLI9vZQkaPSqxychm54I+u6dteSiDzp5aBcukX+CRpP8zF3QMLTYD4kEr0Mh45kWqbznB/Xb+tiDZNyDcU+O+nc+B2HrjU92ENrsWzpztbN6Nz/qGszjjhiU0JfD222qBeFATydJAutlU93PbX/hiIrCZCwSUKz9X0qpTV1XO/i5VvewONH4/yCE4lXo9XYZHKDCO9HxmxlLGxM7mdjlZMSywFYndmqK5Npz5SutPX9Ml7Ap0LpHwrRhuX1eNNkN4L16RKGbkSY1QGv+O7ab3l0Kwmfi4CT/4aeK46YZfb6yypNfQrxf2ZVesS2e11wFYiF4/rzDs/KMBX5fAN/vUv3ABEPj+5DnY29vMS2n3NwlxwD0eXdwdl+O5ScYRl20rZ9xQevlh07toxvOLttnifeocLxMM8M0LvRsaTXGiimjmWOR0yel3h5688I8diF8emUwF9XNfocaSQveU8vKCyYA+BVs2AVH3exGPOzYT66FtJEPAWp0Zu+zSwagPGnnjUUgubZOG2qAFPlnCnIDnPx4G6iEYi1BpjwkIGvSkyXEBVKLZqvMUeSYdEVOojUjSKJLPZ9zDoMEBHOWcY/lduPVotaYHy8C/pBAegqkX7dtM2p9BiHYjO44kYcFeTGgk4lr60DWJ2lpVM/KSyn9Lgtj03JWqoTXG+p2JjbkflY=