env:
        - CODACY_PROJECT_TOKEN=30ded88adc3944479b2de1780b26f01b
language: java

before_install:
        - sudo apt-get install jq
        - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
        - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

notifications:
  slack:
    secure: XLI9vZQkaPSqxychm54I+u6dteSiDzp5aBcukX+CRpP8zF3QMLTYD4kEr0Mh45kWqbznB/Xb+tiDZNyDcU+O+nc+B2HrjU92ENrsWzpztbN6Nz/qGszjjhiU0JfD222qBeFATydJAutlU93PbX/hiIrCZCwSUKz9X0qpTV1XO/i5VvewONH4/yCE4lXo9XYZHKDCO9HxmxlLGxM7mdjlZMSywFYndmqK5Npz5SutPX9Ml7Ap0LpHwrRhuX1eNNkN4L16RKGbkSY1QGv+O7ab3l0Kwmfi4CT/4aeK46YZfb6yypNfQrxf2ZVesS2e11wFYiF4/rzDs/KMBX5fAN/vUv3ABEPj+5DnY29vMS2n3NwlxwD0eXdwdl+O5ScYRl20rZ9xQevlh07toxvOLttnifeocLxMM8M0LvRsaTXGiimjmWOR0yel3h5688I8diF8emUwF9XNfocaSQveU8vKCyYA+BVs2AVH3exGPOzYT66FtJEPAWp0Zu+zSwagPGnnjUUgubZOG2qAFPlnCnIDnPx4G6iEYi1BpjwkIGvSkyXEBVKLZqvMUeSYdEVOojUjSKJLPZ9zDoMEBHOWcY/lduPVotaYHy8C/pBAegqkX7dtM2p9BiHYjO44kYcFeTGgk4lr60DWJ2lpVM/KSyn9Lgtj03JWqoTXG+p2JjbkflY=
